# Generated by Django 4.1.3 on 2022-12-12 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Youtuber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("video_url", models.CharField(max_length=500)),
                ("age", models.IntegerField()),
                ("price", models.IntegerField()),
                ("height", models.IntegerField()),
                ("subs_count", models.IntegerField()),
                ("photo", models.ImageField(upload_to="media/youtubers/%y/%m")),
                ("description", models.TextField()),
                ("category", models.CharField(max_length=100)),
                ("camera_type", models.CharField(max_length=100)),
                ("crew_type", models.CharField(max_length=100)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
