# Generated by Django 4.1.4 on 2022-12-12 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youtubers", "0002_alter_youtuber_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="youtuber",
            name="city",
            field=models.CharField(default="na", max_length=100),
        ),
        migrations.AlterField(
            model_name="youtuber",
            name="camera_type",
            field=models.CharField(
                choices=[("canon", "canon"), ("fuji", "fuji"), ("sony", "sony")],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="youtuber",
            name="category",
            field=models.CharField(
                choices=[
                    ("coding", "coding"),
                    ("vlog", "vlog"),
                    ("cooking", "cooking"),
                    ("unboxing", "unboxing"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="youtuber",
            name="crew_type",
            field=models.CharField(
                choices=[("solo", "solo"), ("small", "small"), ("large", "large")],
                max_length=100,
            ),
        ),
    ]
