# Generated by Django 4.1.3 on 2022-12-08 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webpages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("role", models.CharField(default="NA", max_length=100)),
                ("fb_link", models.CharField(max_length=100)),
                ("insta_link", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("photo", models.ImageField(upload_to="media/team/%y/%m/%d")),
            ],
        ),
    ]
