# Generated by Django 4.1.4 on 2022-12-26 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hiretuber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=255)),
                ("tuber_id", models.IntegerField()),
                ("tuber_name", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("user_id", models.IntegerField(blank=True, null=True)),
                ("created_date", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
